# prettier-ignore
services:
    db:
        image: postgres:16
        restart: always
        env_file:
          - .env.dev
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        ports:
          - ${POSTGRES_PORT}:5432
        volumes:
          - pgdata:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        restart: always
        ports:
          - 8080:8080

volumes:
    pgdata:
