name: Ping Upstash Redis store

on:
    schedule:
        - cron: "0 12 */10 * *"
    workflow_dispatch: # Allows manual triggering for testing

jobs:
    ping-upstash:
        runs-on: ubuntu-latest

        steps:
            - name: Ping Upstash Redis store
              env:
                  TOKEN: ${{ secrets.UPSTASH_REDIS_TOKEN }}
              run: |
                  response=$(curl -X POST -s -o /dev/null -w "%{http_code}" \
                    https://lenient-worm-24059.upstash.io/set/ip \
                    -H "Authorization: Bearer $TOKEN" \
                    -d '"$(uuidgen | tr -d '-')"')

                  if [ "$response" -eq 200 ] || [ "$response" -eq 404 ]; then
                    echo "✅ Upstash Redis ping successful (HTTP $response)"
                  else
                    echo "❌ Upstash Redis ping failed (HTTP $response)"
                    exit 1
                  fi

            - name: Log activity
              run: |
                  echo "🏓 Upstash redis store pinged at $(date)"
                  echo "Next scheduled ping: $(date -d '+10 days')"
