# .github/workflows/supabase-keepalive.yml
name: Ping Supabase

on:
    schedule:
        - cron: "0 0 * * 0,3"
    workflow_dispatch: # Allows manual triggering for testing

jobs:
    ping-database:
        runs-on: ubuntu-latest

        steps:
            - name: Ping Supabase Database
              env:
                  SUPABASE_URL: https://tjvjqelyhjayoefsnfqp.supabase.co
                  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
              run: |
                  # Simple ping using curl to make a database request
                  response=$(curl -s -o /dev/null -w "%{http_code}" \
                    -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
                    -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
                    "$SUPABASE_URL/rest/v1/users")

                  if [ "$response" -eq 200 ] || [ "$response" -eq 404 ]; then
                    echo "✅ Database ping successful (HTTP $response)"
                  else
                    echo "❌ Database ping failed (HTTP $response)"
                    exit 1
                  fi

            - name: Log activity
              run: |
                  echo "🏓 Supabase database pinged at $(date)"
                  echo "Next scheduled ping: $(date -d '+5 days')"
